version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - '8081:8081'
      - '8080:8080'
    container_name: trading-manager-api
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - '80:80'
    container_name: trading-manager-client
