version: '3.8'
services:
  server:
    container_name: trading-manager-api-dev
    build: ./server
    ports:
      - '9000:9000'
      - '8080:8080'
  client:
    container_name: trading-manager-client-dev
    build: ./client
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
