version: '3.8'
services:
  server:
    build: ./server
    ports:
      - '3000:3000'
    container_name: trading-manager-api
  client:
    build: ./client
    ports:
      - '80:80'
    container_name: trading-manager-client
